foreground #e6e1e9
background #141318
cursor #ccbeff
cursor_text_color #141318
selection_foreground #33275e
selection_background #ccbeff

# black
color0 #201f24
color8 #938f99

# red
color1 #ffb4ab
color9 #ffdad6

# green
color2 #ccbeff
color10 #e7deff

# yellow
color3 #eeb8cb
color11 #ffd9e5

# blue
color4 #cac3dc
color12 #e7dff8

# magenta
color5 #eeb8cb
color13 #ffd9e5

# cyan
color6 #cac3dc
color14 #e7dff8

# white
color7 #e6e1e9
color15 #e6e1e9
