foreground #e7e0e8
background #141218
cursor #d2bcfd
cursor_text_color #141218
selection_foreground #38265c
selection_background #d2bcfd

# black
color0 #211f24
color8 #948f99

# red
color1 #ffb4ab
color9 #ffdad6

# green
color2 #d2bcfd
color10 #eaddff

# yellow
color3 #f0b8c6
color11 #ffd9e1

# blue
color4 #cdc2db
color12 #e9def8

# magenta
color5 #f0b8c6
color13 #ffd9e1

# cyan
color6 #cdc2db
color14 #e9def8

# white
color7 #e7e0e8
color15 #e7e0e8
