[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "grow", "--transition-pos", "center"]
set = false

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty-colors.toml"
output_path = "~/.config/alacritty/colors.toml"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout-colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"

[templates.walker]
input_path = "~/.config/matugen/templates/walker-colors.css"
output_path = "~/.config/walker/themes/matugen/style.css"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "pkill -USR1 kitty"

[templates.swayosd]
input_path = "~/.config/matugen/templates/swayosd-colors.css"
output_path = "~/.config/swayosd/style.css"
post_hook = "pkill swayosd-server; setsid swayosd-server >/dev/null 2>&1 &"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock-colors.conf"
output_path = "~/.config/hypr/hyprlock-colors.conf"

[templates.waypaper]
input_path = "~/.config/matugen/templates/waypaper-colors.css"
output_path = "~/.config/waypaper/style.css"

[templates.nvim]
input_path = "~/.config/matugen/templates/nvim-colors.lua"
output_path = "~/.config/nvim/lua/config/matugen-colors.lua"
post_hook = "pkill -USR1 nvim"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk3-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk4-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.qt6ct]
input_path = "~/.config/matugen/templates/qt6ct-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.qt5ct]
input_path = "~/.config/matugen/templates/qt6ct-colors.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/style.css"
post_hook = "swaync-client -rs"
