$accent = rgb(ccbeff)
$accentAlpha = ccbeff
$surface0 = rgb(141318)
$surface0Alpha = 141318
$text = rgb(e6e1e9)
$textAlpha = e6e1e9
$red = rgb(ffb4ab)
$yellow = rgb(eeb8cb)
$base = rgb(201f24)
$wallpaper = /home/daniel/.config/backgrounds/shaded_landscape.png
