$accent = rgb(bfc2ff)
$accentAlpha = bfc2ff
$surface0 = rgb(131318)
$surface0Alpha = 131318
$text = rgb(e4e1e9)
$textAlpha = e4e1e9
$red = rgb(ffb4ab)
$yellow = rgb(e8b9d5)
$base = rgb(1f1f25)
$wallpaper = @{image}
