$accent = rgb(d2bcfd)
$accentAlpha = d2bcfd
$surface0 = rgb(141218)
$surface0Alpha = 141218
$text = rgb(e7e0e8)
$textAlpha = e7e0e8
$red = rgb(ffb4ab)
$yellow = rgb(f0b8c6)
$base = rgb(211f24)
$wallpaper = /home/daniel/.config/backgrounds/arch-rainbow.png
