source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/programs.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/appearance.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybindings.conf
source = ~/.config/hypr/config/rules.conf

# Dynamic colors from matugen
source = ~/.config/hypr/colors.conf
