[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty -o hide_window_decorations=yes --class kitty-scratch"
class = "kitty-scratch"
animation = "fromTop"
size = "75% 60%"
margin = 50

[scratchpads.music]
command = "youtube-music-for-desktop"
class = "YouTube Music for Desktop"
animation = "fromBottom"
size = "75% 60%"
margin = 50
match_by = "class"
