#!/usr/bin/env python3
"""Unit tests for block_ai_attribution: what counts as attribution, and where it can hide —
in a commit message, and in the text gh and az publish.

Markers are assembled from pieces so this file never carries a literal a grep
for stray attribution would flag.

Run: python3 claude/.claude/hooks/test_block_ai_attribution.py
"""

import importlib.util
import io
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import unittest
from collections.abc import Callable
from pathlib import Path
from unittest import mock

_HOOK = Path(__file__).with_name("block_ai_attribution.py")
_spec = importlib.util.spec_from_file_location("block_ai_attribution", _HOOK)
assert _spec and _spec.loader
guard = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(guard)

TRAILER = "Co-" + "authored-" + "by: Claude <noreply@" + "anthropic.com>"
# The line a harness appends to PR descriptions, and its credit without the emoji.
CREDIT = "Generated " + "with [Claude Code](https://claude.com/claude-code)"
HARNESS_LINE = "\U0001f916 " + CREDIT


def run_hook_raw(payload: str) -> subprocess.CompletedProcess[str]:
    """The hook as the harness runs it, fed `payload` on stdin.

    The timeout turns a hook that hangs into a failing test instead of a hung suite.
    """
    return subprocess.run(
        [sys.executable, str(_HOOK)], input=payload, capture_output=True, text=True, check=False, timeout=15
    )


def run_hook(command: str, cwd: str) -> int:
    """The hook as the harness runs it: JSON on stdin, 2 means blocked."""
    return run_hook_raw(json.dumps({"tool_input": {"command": command}, "cwd": cwd})).returncode


def temp_dir(test: unittest.TestCase) -> str:
    """A fresh directory, removed when `test` finishes."""
    path = tempfile.mkdtemp()
    test.addCleanup(shutil.rmtree, path, ignore_errors=True)
    return path


class WhatCounts(unittest.TestCase):
    """The shapes attribution takes, beyond the one wording that prompted this."""

    def test_an_attribution_trailer_counts_whoever_it_names(self):
        for value in ("Claude <x@y>", "GPT-5 <x@y>", "A Person <a@b.c>", "someone"):
            with self.subTest(value=value):
                self.assertIsNotNone(guard.offence("feat: x\n\nCo-" + "authored-by: " + value))

    def test_other_trailer_keys_count_too(self):
        for key in ("Assisted-by", "Generated-by", "AI-Assisted-By", "Claude-Session", "Codex-Session"):
            with self.subTest(key=key):
                self.assertIsNotNone(guard.offence(f"feat: x\n\n{key}: whatever"))

    def test_tool_credits_count_for_every_vendor_not_only_anthropic(self):
        for line in (
            "Generated with Claude Code",
            "Generated by ChatGPT",
            "Written with GPT-5",
            "Co-written with Copilot",
            "Assisted by Gemini",
            "Produced with OpenCode",
            "Claude generated this patch",
        ):
            with self.subTest(line=line):
                self.assertIsNotNone(guard.offence("feat: x\n\n" + line))

    def test_a_vendor_noreply_address_counts(self):
        for address in ("noreply@" + "anthropic.com", "noreply@" + "openai.com"):
            with self.subTest(address=address):
                self.assertIsNotNone(guard.offence("feat: x\n\nSomeone <" + address + ">"))

    def test_an_assistant_session_link_counts(self):
        self.assertIsNotNone(guard.offence("feat: x\n\nhttps://claude.ai/code/session_abc123"))

    def test_the_robot_emoji_counts(self):
        self.assertIsNotNone(guard.offence("feat: x\n\n\U0001f916 with a tool"))

    def test_a_link_to_the_tool_page_counts_whatever_verb_stands_before_it(self):
        for line in (
            "Built using [Claude Code](https://" + "claude.com/claude-code)",
            "See https://www." + "claude.com/claude-code",
            "Made in https://" + "claude.ai/code",
        ):
            with self.subTest(line=line):
                self.assertIsNotNone(guard.offence("feat: x\n\n" + line))


class WhatMustStillPass(unittest.TestCase):
    """A guard that refuses honest commits gets turned off, so these matter as much."""

    def test_a_tool_name_on_its_own_is_not_attribution(self):
        for message in (
            "docs: update CLAUDE.md",
            "feat(api): call the Anthropic messages endpoint",
            "fix: handle a gpt-4 response with no choices",
            "chore: pin the opencode version",
            "docs(claude): describe the hooks under ~/.claude",
            # `cursor` and `cody` are out of the name list for exactly this.
            "fix(ui): move the cursor to the first row when the list is written",
        ):
            with self.subTest(message=message):
                self.assertIsNone(guard.offence(message))

    def test_an_ordinary_message_passes(self):
        self.assertIsNone(guard.offence("fix(qam): claim the band a wide page was leaving under itself\n\nA plain body."))

    def test_the_tool_named_in_prose_without_a_link_is_not_attribution(self):
        self.assertIsNone(guard.offence("feat(hooks): run the guard in every Claude Code session\n\nClaude Code reads it."))

    def test_a_signed_off_by_trailer_is_not_attribution(self):
        self.assertIsNone(guard.offence("feat: x\n\nSigned-off-by: A Person <a@b.c>"))


class MessageFiles(unittest.TestCase):
    def test_every_option_that_names_a_message_file_is_found(self):
        cases = {
            "git commit -F msg.txt": ["msg.txt"],
            "git commit --file msg.txt": ["msg.txt"],
            "git commit --file=msg.txt": ["msg.txt"],
            "git commit -Fmsg.txt": ["msg.txt"],
            "git commit -t tmpl.txt": ["tmpl.txt"],
            "git commit --template=tmpl.txt": ["tmpl.txt"],
            # `-F -` is stdin, and a heredoc body is already in the command string.
            "git commit -F -": [],
            'git commit -m "plain"': [],
        }
        for command, expected in cases.items():
            with self.subTest(command=command):
                self.assertEqual(guard.message_files(command), expected)

    def test_a_command_that_does_not_lex_is_skipped_rather_than_guessed_at(self):
        self.assertEqual(guard.message_files('git commit -F "unclosed'), [])


class EndToEnd(unittest.TestCase):
    """Over the hole that let a real commit through: the message in a file."""

    dir: str = ""
    dirty: Path = Path()
    clean: Path = Path()

    def setUp(self):
        self.dir = temp_dir(self)
        self.dirty = Path(self.dir) / "dirty.txt"
        self.clean = Path(self.dir) / "clean.txt"
        self.dirty.write_text("feat: x\n\n" + TRAILER + "\n")
        self.clean.write_text("feat: x\n\nA plain body.\n")

    def test_the_marker_is_caught_wherever_the_message_comes_from(self):
        cases = {
            f"git commit -F {self.dirty}": 2,
            f"git commit --file={self.dirty}": 2,
            f"git commit -F{self.dirty}": 2,
            f"git -C /tmp commit -F {self.dirty}": 2,
            f"git commit -m 'feat: x\n\n{TRAILER}'": 2,
            f"git commit -F {self.clean}": 0,
            "git commit -m 'feat: x'": 0,
            f"cat {self.dirty}": 0,
        }
        for command, expected in cases.items():
            with self.subTest(command=command.replace(TRAILER, "<trailer>")):
                self.assertEqual(run_hook(command, self.dir), expected)

    def test_a_relative_path_is_read_against_the_command_cwd(self):
        self.assertEqual(run_hook("git commit -F dirty.txt", self.dir), 2)

    def test_an_unreadable_message_file_does_not_break_the_commit(self):
        self.assertEqual(run_hook(f"git commit -F {self.dir}/missing.txt", self.dir), 0)


def heredoc(text: str) -> str:
    """`text` as the `"$(cat <<'EOF' … EOF)"` argument an agent writes for a long body."""
    return f"\"$(cat <<'EOF'\n{text}\nEOF\n)\""


# Every publishing command, with the three ways its text arrives: inline, a
# heredoc in the command string, and a file it reads.
Form = Callable[[str], str]
FAMILIES: dict[str, tuple[Form, Form, Form]] = {
    "gh pr create": (
        lambda t: f"gh pr create --title 'feat: x' --body {shlex.quote(t)}",
        lambda t: f"gh pr create --title 'feat: x' --body {heredoc(t)}",
        lambda p: f"gh pr create --title 'feat: x' --body-file {p}",
    ),
    "gh pr edit": (
        lambda t: f"gh pr edit 7 -b {shlex.quote(t)}",
        lambda t: f"gh pr edit 7 --body {heredoc(t)}",
        lambda p: f"gh pr edit 7 -F{p}",
    ),
    "gh pr comment": (
        lambda t: f"gh pr comment 7 --body={shlex.quote(t)}",
        lambda t: f"gh pr comment 7 -b {heredoc(t)}",
        lambda p: f"gh pr comment 7 -F {p}",
    ),
    "gh pr review": (
        lambda t: f"gh pr review 7 --approve -b {shlex.quote(t)}",
        lambda t: f"gh pr review 7 --comment --body {heredoc(t)}",
        lambda p: f"gh pr review 7 --request-changes --body-file {p}",
    ),
    "gh pr merge": (
        lambda t: f"gh pr merge 7 --squash --subject 'feat: x' --body {shlex.quote(t)}",
        lambda t: f"gh pr merge 7 --squash -t 'feat: x' -b {heredoc(t)}",
        lambda p: f"gh pr merge 7 --squash --body-file={p}",
    ),
    "gh issue create": (
        lambda t: f"gh issue create -t 'Bug' -b {shlex.quote(t)}",
        lambda t: f"gh issue create --title 'Bug' --body {heredoc(t)}",
        lambda p: f"gh issue create --title 'Bug' -F {p}",
    ),
    "gh issue edit": (
        lambda t: f"gh issue edit 3 --body {shlex.quote(t)}",
        lambda t: f"gh issue edit 3 --body {heredoc(t)}",
        lambda p: f"gh issue edit 3 --body-file {p}",
    ),
    "gh issue comment": (
        lambda t: f"gh issue comment 3 -b {shlex.quote(t)}",
        lambda t: f"gh issue comment 3 --body {heredoc(t)}",
        lambda p: f"gh issue comment 3 -F {p}",
    ),
    "gh release create": (
        lambda t: f"gh release create v1.0.0 --title v1.0.0 --notes {shlex.quote(t)}",
        lambda t: f"gh release create v1.0.0 -t v1.0.0 -n {heredoc(t)}",
        lambda p: f"gh release create v1.0.0 --notes-file {p} dist/app.zip",
    ),
    "gh release edit": (
        lambda t: f"gh release edit v1.0.0 -n {shlex.quote(t)}",
        lambda t: f"gh release edit v1.0.0 --notes {heredoc(t)}",
        lambda p: f"gh release edit v1.0.0 -F {p}",
    ),
    "gh api": (
        lambda t: f"gh api repos/o/r/issues/3/comments -f body={shlex.quote(t)}",
        lambda t: f"gh api repos/o/r/issues/3/comments --raw-field body={heredoc(t)}",
        lambda p: f"gh api repos/o/r/issues/3/comments -F body=@{p}",
    ),
    "az repos pr create": (
        lambda t: f"az repos pr create --title 'feat: x' --description {shlex.quote(t)}",
        lambda t: f"az repos pr create --title 'feat: x' --description {heredoc(t)}",
        lambda p: f"az repos pr create --title 'feat: x' --description @{p}",
    ),
    "az repos pr update": (
        lambda t: f"az repos pr update --id 5 --description 'First line.' {shlex.quote(t)}",
        lambda t: f"az repos pr update --id 5 --description {heredoc(t)}",
        lambda p: f"az repos pr update --id 5 --description @{p} --title 'feat: x'",
    ),
    "az repos pr create -d": (
        lambda t: f"az repos pr create --title 'feat: x' -d 'First line.' {shlex.quote(t)}",
        lambda t: f"az repos pr create --title 'feat: x' -d {heredoc(t)}",
        lambda p: f"az repos pr create -d @{p} --title 'feat: x'",
    ),
}

MARKED_BODIES = {
    "the robot line": "Adds the export button.\n\n" + HARNESS_LINE,
    "the credit without the emoji": "Adds the export button.\n\n" + CREDIT,
    "a co-author trailer": "Adds the export button.\n\n" + TRAILER,
}
CLEAN_BODIES = {
    "a plain body": "Adds the export button.\n\nIt's wired to the existing endpoint.",
    "a body naming CLAUDE.md": "Documents the rule in CLAUDE.md and the hooks under ~/.claude.",
    "a body about a generated file": "Regenerates the lockfile; the generated file is checked in.",
}


class PublishedText(unittest.TestCase):
    """What gh and az publish is held to the same patterns as a commit message."""

    dir: str = ""

    def setUp(self):
        self.dir = temp_dir(self)

    def body_file(self, name: str, text: str) -> str:
        path = Path(self.dir) / name
        path.write_text(text + "\n")
        return str(path)

    def forms(self, family: str, body: str):
        inline, in_heredoc, from_file = FAMILIES[family]
        yield "inline", inline(body)
        yield "heredoc", in_heredoc(body)
        yield "file", from_file(self.body_file("body.md", body))

    def test_attribution_is_blocked_in_every_family_and_form(self):
        for family in FAMILIES:
            for marker, body in MARKED_BODIES.items():
                for form, command in self.forms(family, body):
                    with self.subTest(family=family, marker=marker, form=form):
                        self.assertIsNotNone(guard.publish_block(command, self.dir))

    def test_honest_text_passes_in_every_family_and_form(self):
        for family in FAMILIES:
            for kind, body in CLEAN_BODIES.items():
                for form, command in self.forms(family, body):
                    with self.subTest(family=family, body=kind, form=form):
                        self.assertIsNone(guard.publish_block(command, self.dir))

    def test_the_reason_names_the_command_and_the_finding(self):
        reason = guard.publish_block(FAMILIES["gh pr create"][0]("Adds a button.\n\n\U0001f916 Shipped"), self.dir) or ""
        self.assertIn("gh pr create", reason)
        self.assertIn("robot emoji", reason)
        path = self.body_file("notes.md", MARKED_BODIES["a co-author trailer"])
        reason = guard.publish_block(f"gh release edit v1 --notes-file {path}", self.dir) or ""
        self.assertIn("a file the gh release edit command reads", reason)
        self.assertIn("trailer", reason)

    def test_a_relative_body_file_is_read_against_the_command_cwd(self):
        self.body_file("body.md", MARKED_BODIES["a co-author trailer"])
        self.assertIsNotNone(guard.publish_block("gh pr comment 7 -F body.md", self.dir))

    def test_a_heredoc_on_stdin_is_read(self):
        body = MARKED_BODIES["the robot line"]
        for command in (
            f"gh pr create --title x --body-file - <<'EOF'\n{body}\nEOF",
            f"gh api repos/o/r/issues/3/comments --input - <<'EOF'\n{json.dumps({'body': body})}\nEOF",
        ):
            with self.subTest(command=command.split(" <<")[0]):
                self.assertIsNotNone(guard.publish_block(command, self.dir))

    def test_text_put_together_earlier_in_the_same_call_is_caught(self):
        body = MARKED_BODIES["a co-author trailer"]
        later = str(Path(self.dir) / "written-in-this-call.md")
        for command in (
            f"cat > {later} <<'EOF'\n{body}\nEOF\ngh pr create --title x --body-file {later}",
            f'BODY={heredoc(body)} && gh pr create --title x --body "$BODY"',
            f'BODY={heredoc(body)} && gh api repos/o/r/issues/3/comments -f body="$BODY"',
        ):
            with self.subTest(command=command.split("\n")[0]):
                self.assertIsNotNone(guard.publish_block(command, self.dir))

    def test_a_stdin_body_from_elsewhere_does_not_block_on_its_own(self):
        self.assertIsNone(guard.publish_block("make-notes | gh pr create --title x --body-file -", self.dir))

    def test_a_body_piped_from_cat_is_read(self):
        path = self.body_file("body.md", MARKED_BODIES["the robot line"])
        self.assertIsNotNone(guard.publish_block(f"cat {path} | gh pr create --title x --body-file -", self.dir))

    def test_a_file_read_into_the_command_is_read(self):
        dirty = self.body_file("dirty.md", MARKED_BODIES["a co-author trailer"])
        self.body_file("clean.md", CLEAN_BODIES["a plain body"])
        for command, blocked in (
            ('gh pr create --title x --body "$(cat dirty.md)"', True),
            ('gh pr comment 7 --body "$(< dirty.md)"', True),
            ('gh pr comment 7 --body "$(<dirty.md)"', True),
            ('gh api repos/o/r/issues/3/comments -f body="$(cat dirty.md)"', True),
            ('gh issue create -t x -b "$(cat -- clean.md dirty.md)"', True),
            ('gh pr create --title x --body "$(cat clean.md)"', False),
            # `> dirty.md` is where cat writes, not what it reads.
            (f"cat > {dirty} <<'EOF'\nA plain body.\nEOF\ngh pr create --title x --body-file clean.md", False),
        ):
            with self.subTest(command=command):
                self.assertEqual(guard.publish_block(command, self.dir) is not None, blocked)

    def test_a_read_only_command_s_cat_is_not_read(self):
        self.body_file("dirty.md", MARKED_BODIES["a co-author trailer"])
        self.assertIsNone(guard.publish_block("cat dirty.md && gh pr view 7", self.dir))

    def test_a_relative_body_file_follows_a_cd_earlier_in_the_command(self):
        sub = Path(self.dir) / "sub"
        sub.mkdir()
        (sub / "body.md").write_text(MARKED_BODIES["a co-author trailer"])
        for command, blocked in (
            (f"cd {sub} && gh pr create --title x --body-file body.md", True),
            ("cd sub && gh pr create --title x --body-file body.md", True),
            ('cd sub; gh pr create --title x --body "$(cat body.md)"', True),
            ("cd sub && gh api repos/o/r/issues -F body=@body.md", True),
            # Not followed: the directory is not in the command.
            ("cd - && gh pr create --title x --body-file body.md", False),
            ("cd $SUB && gh pr create --title x --body-file body.md", False),
        ):
            with self.subTest(command=command):
                self.assertEqual(guard.publish_block(command, self.dir) is not None, blocked)

    def test_a_cat_in_backticks_or_behind_a_prefix_is_read(self):
        self.body_file("dirty.md", MARKED_BODIES["a co-author trailer"])
        for command in (
            'gh pr create --title x --body "`cat dirty.md`"',
            "gh pr create --title x --body `cat dirty.md`",
            'gh pr create --title x --body "$(LC_ALL=C cat dirty.md)"',
            'gh pr create --title x --body "$(command cat dirty.md)"',
            'gh issue comment 3 --body "$(sudo cat dirty.md)"',
        ):
            with self.subTest(command=command):
                self.assertIsNotNone(guard.publish_block(command, self.dir))

    def test_cat_reading_its_stdin_from_a_file_is_read(self):
        self.body_file("dirty.md", MARKED_BODIES["a co-author trailer"])
        for command in ('gh pr create --title x --body "$(cat < dirty.md)"', 'gh pr create --title x --body "$(cat <dirty.md)"'):
            with self.subTest(command=command):
                self.assertIsNotNone(guard.publish_block(command, self.dir))

    def test_a_cd_inside_a_subshell_stays_there(self):
        # body.md here carries the marker; sub/body.md does not.
        self.body_file("body.md", MARKED_BODIES["a co-author trailer"])
        (Path(self.dir) / "sub").mkdir()
        (Path(self.dir) / "sub" / "body.md").write_text(CLEAN_BODIES["a plain body"])
        for command, blocked in (
            ("(cd sub && ls); gh pr create --title x --body-file body.md", True),
            ("X=$(cd sub && ls); gh pr create --title x --body-file body.md", True),
            ("X=`cd sub`; gh pr create --title x --body-file body.md", True),
            ('gh pr create --title x --body "$(cd sub && pwd)" --body-file body.md', True),
            ("cd sub && gh pr create --title x --body-file body.md", False),
            ("(cd sub && gh pr create --title x --body-file body.md)", False),
            ('cd sub && gh pr create --title x --body "$(cat body.md)"', False),
        ):
            with self.subTest(command=command):
                self.assertEqual(guard.publish_block(command, self.dir) is not None, blocked)

    def test_close_and_reopen_comments_are_checked(self):
        for command in ("gh pr close 7 -c", "gh pr reopen 7 --comment", "gh issue close 3 --comment", "gh issue reopen 3 -c"):
            with self.subTest(command=command):
                self.assertIsNotNone(guard.publish_block(f"{command} {shlex.quote(MARKED_BODIES['the robot line'])}", self.dir))
                self.assertIsNone(guard.publish_block(f"{command} {shlex.quote(CLEAN_BODIES['a plain body'])}", self.dir))

    def test_option_and_line_continuation_spellings(self):
        self.body_file("body.md", MARKED_BODIES["a co-author trailer"])
        for command in (
            "gh pr create --title x -F=body.md",
            "gh release edit v1 -F=body.md",
            "gh \\\n  pr create --title x --body-file body.md",
            "gh \\\n  pr create --title x --body " + shlex.quote(MARKED_BODIES["the robot line"]),
        ):
            with self.subTest(command=command):
                self.assertIsNotNone(guard.publish_block(command, self.dir))

    def test_a_link_to_the_tool_page_blocks_published_text(self):
        body = "Adds the export button.\n\nBuilt using [Claude Code](https://" + "claude.com/claude-code)"
        self.assertIsNotNone(guard.publish_block(f"gh pr create --title x --body {shlex.quote(body)}", self.dir))
        prose = "Adds a hook that every Claude Code session runs."
        self.assertIsNone(guard.publish_block(f"gh pr create --title x --body {shlex.quote(prose)}", self.dir))

    def test_a_publishing_command_is_found_in_a_chain(self):
        body = MARKED_BODIES["the credit without the emoji"]
        for command in (
            f"cd {self.dir} && gh pr create --title x --body {shlex.quote(body)} 2>&1 | tail -3",
            f"git push -u origin HEAD; URL=$(gh pr create --title x -b {shlex.quote(body)}) && echo $URL",
        ):
            with self.subTest(command=command[:40]):
                self.assertIsNotNone(guard.publish_block(command, self.dir))

    def test_commands_that_only_read_are_left_alone(self):
        for command in (
            "gh pr view 7 --json body -q .body | grep -c '\U0001f916'",
            "gh issue list --search " + shlex.quote(CREDIT),
            "gh release view v1.0.0",
            "az repos pr list --status active",
        ):
            with self.subTest(command=command):
                self.assertIsNone(guard.publish_block(command, self.dir))


class GhApi(unittest.TestCase):
    """`gh api` is judged on what it sends, never on what it reads."""

    dir: str = ""

    def setUp(self):
        self.dir = temp_dir(self)

    def test_a_field_value_is_checked(self):
        marked = shlex.quote(MARKED_BODIES["the robot line"])
        clean = shlex.quote(CLEAN_BODIES["a plain body"])
        self.assertIsNotNone(guard.publish_block(f"gh api repos/o/r/pulls/7 -X PATCH -f body={marked}", self.dir))
        self.assertIsNone(guard.publish_block(f"gh api repos/o/r/pulls/7 -X PATCH -f body={clean}", self.dir))

    def test_an_input_file_is_read(self):
        path = Path(self.dir) / "payload.json"
        path.write_text(json.dumps({"body": MARKED_BODIES["a co-author trailer"]}))
        self.assertIsNotNone(guard.publish_block(f"gh api repos/o/r/issues --input {path}", self.dir))

    def test_the_endpoint_and_the_jq_filter_are_not_checked(self):
        jq = shlex.quote('.[] | select(.user.login=="claude") | .created_at')
        self.assertIsNone(guard.publish_block(f"gh api repos/anthropics/claude-code/issues -f title=Bug --jq {jq}", self.dir))

    def test_an_explicit_get_sends_nothing_to_publish(self):
        query = shlex.quote("author:app/" + "copilot created:>2024-01-01")
        self.assertIsNone(guard.publish_block(f"gh api -X GET search/issues -f q={query}", self.dir))
        # Without `-X GET` the same fields make gh send a POST.
        self.assertIsNotNone(guard.publish_block(f"gh api search/issues -f q={query}", self.dir))

    def test_a_raw_field_sends_an_at_path_as_written(self):
        path = Path(self.dir) / "body.md"
        path.write_text(MARKED_BODIES["a co-author trailer"])
        self.assertIsNone(guard.publish_block(f"gh api repos/o/r/issues -f body=@{path}", self.dir))
        self.assertIsNotNone(guard.publish_block(f"gh api repos/o/r/issues -F body=@{path}", self.dir))

    def test_json_escapes_are_read_as_what_they_stand_for(self):
        # json.dumps writes the line breaks as `\n` and the emoji as a `\u` escape;
        # these markers show only once that is decoded.
        for marker, body in (
            ("a trailer naming a person", "Adds the button.\n\nCo-" + "authored-by: A Person <a@b.c>"),
            ("the emoji alone", "Adds the button.\n\n\U0001f916 Shipped"),
        ):
            payload = json.dumps({"title": "x", "body": body})
            self.assertIsNone(guard.offence(payload))
            path = Path(self.dir) / "payload.json"
            path.write_text(payload)
            for command in (
                f"gh api repos/o/r/issues --input {path}",
                f"gh api repos/o/r/issues --input - <<'EOF'\n{payload}\nEOF",
            ):
                with self.subTest(marker=marker, command=command.split(" <<")[0]):
                    self.assertIsNotNone(guard.publish_block(command, self.dir))
        path.write_text(json.dumps({"body": CLEAN_BODIES["a plain body"]}))
        self.assertIsNone(guard.publish_block(f"gh api repos/o/r/issues --input {path}", self.dir))


class SearchPatterns(unittest.TestCase):
    """A grep/rg pattern names what to find; it is not text that gets published."""

    dir: str = ""

    def setUp(self):
        self.dir = temp_dir(self)
        (Path(self.dir) / "clean.md").write_text(CLEAN_BODIES["a plain body"])
        (Path(self.dir) / "dirty.md").write_text(MARKED_BODIES["the robot line"])

    def test_a_check_for_a_credit_line_passes(self):
        robot = "'\U0001f916'"
        for command in (
            f'gh pr edit 7 --body "$(gh pr view 7 --json body -q .body | grep -v {robot})"',
            f"! grep -q {robot} clean.md && gh pr create --title x --body-file clean.md",
            f"grep -n -e {robot} clean.md; gh pr create --title x -F clean.md",
            f"grep -ve {robot} clean.md > out.md && gh pr create --title x -F clean.md",
            f"grep --regexp={robot} clean.md || gh pr create --title x -F clean.md",
            f"rg -q -- {robot} clean.md || gh issue comment 3 -F clean.md",
            f"LC_ALL=C grep -m 1 -c {shlex.quote(CREDIT)} clean.md && gh pr create --title x -F clean.md",
            # A pattern that names a publishing command does not make one.
            "grep -c 'gh pr create' clean.md; cat dirty.md",
        ):
            with self.subTest(command=command):
                self.assertIsNone(guard.publish_block(command, self.dir))

    def test_what_would_be_published_is_still_checked(self):
        robot = "'\U0001f916'"
        for command in (
            f"! grep -q {robot} dirty.md && gh pr create --title x --body-file dirty.md",
            f"! grep -q {robot} clean.md && gh pr create --title x --body 'Done. \U0001f916'",
            f"grep -v {robot} clean.md && gh pr create --title x --body " + shlex.quote(MARKED_BODIES["a co-author trailer"]),
            'gh api repos/o/r/issues -f body="$(grep -v x clean.md) \U0001f916"',
        ):
            with self.subTest(command=command):
                self.assertIsNotNone(guard.publish_block(command, self.dir))

    def test_an_rg_replacement_is_not_mistaken_for_the_pattern(self):
        # rg's `-r` takes the replacement text; the pattern is the word after it.
        command = "rg -r 'x' '\U0001f916' clean.md || gh pr create --title x -F clean.md"
        self.assertIsNone(guard.publish_block(command, self.dir))

    def test_a_commit_chain_leaves_the_pattern_out_and_still_reads_the_message_file(self):
        rewrite = "git log -1 --format=%B | grep -v '\U0001f916' > m.txt && git commit --amend -F m.txt"
        message = Path(self.dir) / "m.txt"
        message.write_text("feat: x\n\nA plain body.\n")
        self.assertIsNone(guard.commit_block(rewrite, self.dir))
        message.write_text("feat: x\n\n" + TRAILER + "\n")
        self.assertIsNotNone(guard.commit_block(rewrite, self.dir))
        message.write_text("feat: x\n\nA plain body.\n")
        self.assertIsNotNone(guard.commit_block(f"{rewrite} -m 'feat: y \U0001f916'", self.dir))


class FilesThatAreNotPlainText(unittest.TestCase):
    """Only regular files are read, and only their start: nothing may stall the Bash call."""

    dir: str = ""

    def setUp(self):
        self.dir = temp_dir(self)

    def test_a_fifo_or_a_device_is_not_read(self):
        fifo = Path(self.dir) / "pipe"
        os.mkfifo(fifo)
        for command in (
            f'gh pr create --title x --body "$(cat {fifo})"',
            f"gh pr create --title x --body-file {fifo}",
            f"gh api repos/o/r/issues --input {fifo}",
            f"git commit -F {fifo}",
            'gh pr create --title x --body "$(cat /dev/zero | head -c 10)"',
            "gh pr create --title x --body-file /dev/zero",
        ):
            with self.subTest(command=command):
                self.assertEqual(run_hook(command, self.dir), 0)

    def test_only_the_start_of_a_huge_file_is_read(self):
        path = Path(self.dir) / "big.md"
        filler = "a" * (guard.MAX_READ + 10) + "\n"
        path.write_text(TRAILER + "\n" + filler)
        self.assertIsNotNone(guard.publish_block(f"gh pr create --title x --body-file {path}", self.dir))
        path.write_text(filler + TRAILER + "\n")
        self.assertIsNone(guard.publish_block(f"gh pr create --title x --body-file {path}", self.dir))


class ParseCommands(unittest.TestCase):
    """The shell reader behind the gh and az checks."""

    def parsed(self, command: str) -> list[tuple[list[str], list[str]]]:
        return [(c.words, c.heredocs) for c in guard.parse_commands(command)]

    def test_separators_split_commands_and_redirections_do_not(self):
        self.assertEqual(
            self.parsed("cd /x && gh pr view 1 2>&1 | tail -3; echo done &>/dev/null"),
            [
                (["cd", "/x"], []),
                (["gh", "pr", "view", "1", "2>&1"], []),
                (["tail", "-3"], []),
                (["echo", "done", "&>/dev/null"], []),
            ],
        )

    def test_a_heredoc_body_belongs_to_its_command_even_with_apostrophes_and_pipes(self):
        self.assertEqual(
            self.parsed("gh pr create -F - <<'EOF' && echo ok\nIt's done | a table |\nEOF\nls"),
            [(["gh", "pr", "create", "-F", "-"], ["It's done | a table |"]), (["echo", "ok"], []), (["ls"], [])],
        )

    def test_a_command_substitution_is_read_as_commands_too(self):
        parsed = self.parsed("gh pr edit 1 --body \"$(cat <<'EOF'\nSays \"hi\"\nEOF\n)\"")
        self.assertEqual(parsed[0], (["cat"], ['Says "hi"']))
        self.assertEqual(parsed[1][0][:5], ["gh", "pr", "edit", "1", "--body"])
        self.assertEqual(len(parsed[1][0]), 6)

    def test_a_here_string_is_not_a_heredoc(self):
        self.assertEqual(self.parsed('gh pr edit 1 -F - <<< "$x"'), [(["gh", "pr", "edit", "1", "-F", "-", "<<<", '"$x"'], [])])

    def test_a_comment_is_skipped(self):
        self.assertEqual(self.parsed("gh pr view 1 # it's a note\nls"), [(["gh", "pr", "view", "1"], []), (["ls"], [])])

    def test_input_it_cannot_follow_does_not_raise(self):
        for command in ('gh pr create -F "unclosed', "gh pr create -b $(unclosed", "cat <<EOF", "gh api x -f", "\\"):
            with self.subTest(command=command):
                guard.parse_commands(command)
                self.assertIsNone(guard.publish_block(command, "/nonexistent"))

    def test_nesting_too_deep_to_follow_does_not_raise(self):
        command = "gh pr create -b " + "$(" * 5000 + "x" + ")" * 5000
        guard.parse_commands(command)
        self.assertIsNone(guard.publish_block(command, "/nonexistent"))

    def test_a_line_continuation_between_words_is_a_blank(self):
        self.assertEqual(self.parsed("gh \\\n  pr view 1"), [(["gh", "pr", "view", "1"], [])])

    def test_backticks_are_read_as_commands_like_a_substitution(self):
        parsed = self.parsed('gh pr edit 1 --body "`cat a.md`" `echo -t` x')
        self.assertEqual([words for words, _ in parsed[:2]], [["cat", "a.md"], ["echo", "-t"]])
        self.assertEqual(parsed[2][0][:4], ["gh", "pr", "edit", "1"])

    def test_a_subshell_or_substitution_opens_a_group_inside_its_parent(self):
        commands = guard.parse_commands("a; (b; c); d $(e) `f`")
        groups = {c.words[0]: c.group for c in commands}
        self.assertEqual(groups["a"], groups["d"])
        self.assertEqual(groups["b"], groups["c"])
        for inner in ("b", "e", "f"):
            with self.subTest(inner=inner):
                self.assertNotEqual(groups[inner], groups["a"])
                self.assertEqual(groups[inner][: len(groups["a"])], groups["a"])


class PublishEndToEnd(unittest.TestCase):
    """The hook as the harness runs it, over the publishing commands."""

    def test_exit_codes(self):
        cases = {
            "gh pr create --title x --body " + shlex.quote(MARKED_BODIES["the robot line"]): 2,
            "gh api repos/o/r/issues/3/comments -f body=" + shlex.quote(MARKED_BODIES["a co-author trailer"]): 2,
            "az repos pr create --title x --description " + shlex.quote(MARKED_BODIES["the credit without the emoji"]): 2,
            "gh pr create --title x --body " + shlex.quote(CLEAN_BODIES["a body naming CLAUDE.md"]): 0,
            "gh pr view 7": 0,
        }
        for command, expected in cases.items():
            with self.subTest(command=command[:30]):
                self.assertEqual(run_hook(command, tempfile.gettempdir()), expected)

    def test_input_of_the_wrong_shape_is_let_through_quietly(self):
        for payload in ("[]", '"text"', "3", '{"tool_input": []}', '{"tool_input": {"command": 5}}', "not json"):
            with self.subTest(payload=payload):
                result = run_hook_raw(payload)
                self.assertEqual((result.returncode, result.stderr), (0, ""))

    def test_an_error_inside_the_hook_lets_the_call_through(self):
        payload = json.dumps({"tool_input": {"command": "gh pr create --title x --body y"}, "cwd": "/"})
        with (
            mock.patch.object(guard, "publishing_sources", side_effect=RuntimeError("boom")),
            mock.patch.object(sys, "stdin", io.StringIO(payload)),
            mock.patch.object(sys, "stderr", io.StringIO()) as stderr,
        ):
            self.assertEqual(guard.main(), 0)
        self.assertIn("boom", stderr.getvalue())


if __name__ == "__main__":
    unittest.main()
