#!/usr/bin/env python3
"""Unit tests for block_ai_attribution: what counts as attribution, and where it can hide.

Markers are assembled from pieces so this file never carries a literal a grep
for stray attribution would flag.

Run: python3 claude/.claude/hooks/test_block_ai_attribution.py
"""

import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

_HOOK = Path(__file__).with_name("block_ai_attribution.py")
_spec = importlib.util.spec_from_file_location("block_ai_attribution", _HOOK)
assert _spec and _spec.loader
guard = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(guard)

TRAILER = "Co-" + "authored-" + "by: Claude <noreply@" + "anthropic.com>"


def run_hook(command: str, cwd: str) -> int:
    """The hook as the harness runs it: JSON on stdin, 2 means blocked."""
    payload = json.dumps({"tool_input": {"command": command}, "cwd": cwd})
    return subprocess.run([sys.executable, str(_HOOK)], input=payload, capture_output=True, text=True).returncode


class WhatCounts(unittest.TestCase):
    """The shapes attribution takes, beyond the one wording that prompted this."""

    def test_an_attribution_trailer_counts_whoever_it_names(self):
        for value in ("Claude <x@y>", "GPT-5 <x@y>", "A Person <a@b.c>", "someone"):
            with self.subTest(value=value):
                self.assertIsNotNone(guard.offence("feat: x\n\nCo-" + "authored-by: " + value))

    def test_other_trailer_keys_count_too(self):
        for key in ("Assisted-by", "Generated-by", "AI-Assisted-By", "Claude-Session", "Codex-Session"):
            with self.subTest(key=key):
                self.assertIsNotNone(guard.offence(f"feat: x\n\n{key}: whatever"))

    def test_tool_credits_count_for_every_vendor_not_only_anthropic(self):
        for line in (
            "Generated with Claude Code",
            "Generated by ChatGPT",
            "Written with GPT-5",
            "Co-written with Copilot",
            "Assisted by Gemini",
            "Produced with OpenCode",
            "Claude generated this patch",
        ):
            with self.subTest(line=line):
                self.assertIsNotNone(guard.offence("feat: x\n\n" + line))

    def test_a_vendor_noreply_address_counts(self):
        for address in ("noreply@" + "anthropic.com", "noreply@" + "openai.com"):
            with self.subTest(address=address):
                self.assertIsNotNone(guard.offence("feat: x\n\nSomeone <" + address + ">"))

    def test_an_assistant_session_link_counts(self):
        self.assertIsNotNone(guard.offence("feat: x\n\nhttps://claude.ai/code/session_abc123"))

    def test_the_robot_emoji_counts(self):
        self.assertIsNotNone(guard.offence("feat: x\n\n\U0001f916 with a tool"))


class WhatMustStillPass(unittest.TestCase):
    """A guard that refuses honest commits gets turned off, so these matter as much."""

    def test_a_tool_name_on_its_own_is_not_attribution(self):
        for message in (
            "docs: update CLAUDE.md",
            "feat(api): call the Anthropic messages endpoint",
            "fix: handle a gpt-4 response with no choices",
            "chore: pin the opencode version",
            "docs(claude): describe the hooks under ~/.claude",
            # `cursor` and `cody` are out of the name list for exactly this.
            "fix(ui): move the cursor to the first row when the list is written",
        ):
            with self.subTest(message=message):
                self.assertIsNone(guard.offence(message))

    def test_an_ordinary_message_passes(self):
        self.assertIsNone(guard.offence("fix(qam): claim the band a wide page was leaving under itself\n\nA plain body."))

    def test_a_signed_off_by_trailer_is_not_attribution(self):
        self.assertIsNone(guard.offence("feat: x\n\nSigned-off-by: A Person <a@b.c>"))


class MessageFiles(unittest.TestCase):
    def test_every_option_that_names_a_message_file_is_found(self):
        cases = {
            "git commit -F msg.txt": ["msg.txt"],
            "git commit --file msg.txt": ["msg.txt"],
            "git commit --file=msg.txt": ["msg.txt"],
            "git commit -Fmsg.txt": ["msg.txt"],
            "git commit -t tmpl.txt": ["tmpl.txt"],
            "git commit --template=tmpl.txt": ["tmpl.txt"],
            # `-F -` is stdin, and a heredoc body is already in the command string.
            "git commit -F -": [],
            'git commit -m "plain"': [],
        }
        for command, expected in cases.items():
            with self.subTest(command=command):
                self.assertEqual(guard.message_files(command), expected)

    def test_a_command_that_does_not_lex_is_skipped_rather_than_guessed_at(self):
        self.assertEqual(guard.message_files('git commit -F "unclosed'), [])


class EndToEnd(unittest.TestCase):
    """Over the hole that let a real commit through: the message in a file."""

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.dirty = Path(self.dir) / "dirty.txt"
        self.clean = Path(self.dir) / "clean.txt"
        self.dirty.write_text("feat: x\n\n" + TRAILER + "\n")
        self.clean.write_text("feat: x\n\nA plain body.\n")

    def test_the_marker_is_caught_wherever_the_message_comes_from(self):
        cases = {
            f"git commit -F {self.dirty}": 2,
            f"git commit --file={self.dirty}": 2,
            f"git commit -F{self.dirty}": 2,
            f"git -C /tmp commit -F {self.dirty}": 2,
            f"git commit -m 'feat: x\n\n{TRAILER}'": 2,
            f"git commit -F {self.clean}": 0,
            "git commit -m 'feat: x'": 0,
            f"cat {self.dirty}": 0,
        }
        for command, expected in cases.items():
            with self.subTest(command=command.replace(TRAILER, "<trailer>")):
                self.assertEqual(run_hook(command, self.dir), expected)

    def test_a_relative_path_is_read_against_the_command_cwd(self):
        self.assertEqual(run_hook("git commit -F dirty.txt", self.dir), 2)

    def test_an_unreadable_message_file_does_not_break_the_commit(self):
        self.assertEqual(run_hook(f"git commit -F {self.dir}/missing.txt", self.dir), 0)


if __name__ == "__main__":
    unittest.main()
