[colors.primary]
background = "#141318"
foreground = "#e6e1e9"

[colors.cursor]
text = "#141318"
cursor = "#ccbeff"

[colors.selection]
text = "#33275e"
background = "#ccbeff"

[colors.normal]
black = "#201f24"
red = "#ffb4ab"
green = "#ccbeff"
yellow = "#eeb8cb"
blue = "#cac3dc"
magenta = "#eeb8cb"
cyan = "#cac3dc"
white = "#e6e1e9"

[colors.bright]
black = "#938f99"
red = "#ffdad6"
green = "#e7deff"
yellow = "#ffd9e5"
blue = "#e7dff8"
magenta = "#ffd9e5"
cyan = "#e7dff8"
white = "#e6e1e9"
