-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '{{colors.background.default.hex}}',
  base01 = '{{colors.surface_container_lowest.default.hex}}',
  base02 = '{{colors.surface_container_low.default.hex}}',
  base03 = '{{colors.outline_variant.default.hex}}',
  base04 = '{{colors.on_surface_variant.default.hex}}',
  base05 = '{{colors.on_surface.default.hex}}',
  base06 = '{{colors.inverse_on_surface.default.hex}}',
  base07 = '{{colors.surface_bright.default.hex}}',
  base08 = '{{colors.error.default.hex}}',
  base09 = '{{colors.tertiary.default.hex}}',
  base0A = '{{colors.secondary.default.hex}}',
  base0B = '{{colors.primary.default.hex}}',
  base0C = '{{colors.tertiary_container.default.hex}}',
  base0D = '{{colors.primary_container.default.hex}}',
  base0E = '{{colors.secondary_container.default.hex}}',
  base0F = '{{colors.error_container.default.hex}}',
})

-- Custom highlights fuer besseren Kontrast
local function set_hl_multiple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.background.default.hex}}',
})

set_hl_multiple({ 'TSComment', 'Comment' }, {
  fg = '{{colors.on_tertiary_container.default.hex}}',
})

set_hl_multiple({ 'TSMethod', 'Method' }, {
  fg = '{{colors.tertiary.default.hex}}',
})

set_hl_multiple({ 'TSFunction', 'Function' }, {
  fg = '{{colors.secondary.default.hex}}',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '{{colors.inverse_primary.default.hex}}',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '{{colors.surface_container_lowest.default.hex}}',
  fg = '{{colors.primary.default.hex}}',
})

-- CursorLine mit subtiler Hintergrundfarbe
vim.api.nvim_set_hl(0, 'CursorLine', {
  bg = '{{colors.surface_container_highest.default.hex}}',
})
vim.api.nvim_set_hl(0, 'CursorLineNr', {
  fg = '{{colors.primary.default.hex}}',
  bg = '{{colors.surface_container_highest.default.hex}}',
  bold = true,
})
-- LineNr auch anpassen damit es konsistent ist
vim.api.nvim_set_hl(0, 'LineNr', {
  fg = '{{colors.outline.default.hex}}',
})

-- Neo-tree transparenter Hintergrund
set_hl_multiple({ 'NeoTreeNormal', 'NeoTreeNormalNC', 'NeoTreeEndOfBuffer' }, {
  bg = 'NONE',
})
vim.api.nvim_set_hl(0, 'NeoTreeWinSeparator', {
  fg = '{{colors.surface_container.default.hex}}',
  bg = 'NONE',
})
-- NeoTree CursorLine auch transparent
vim.api.nvim_set_hl(0, 'NeoTreeCursorLine', {
  bg = '{{colors.surface_container_high.default.hex}}',
})
