#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = chmod +x ~/.config/waybar/scripts/*
exec-once = waybar
exec-once = swww-daemon
exec-once = hypridle
exec-once = /usr/lib/pam_kwallet_init
exec-once = kwalletd6
exec-once = swayosd-server
exec-once = swaync
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = elephant
exec-once = walker --gapplication-service
exec-once = pypr
# exec-once = waypaper-engine daemon  # disabled - crashes and causes 5min coredump
