#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Qt-Theming für Dolphin und andere Qt-Apps
env = QT_QPA_PLATFORMTHEME,qt6ct

# Electron-Apps nativ unter Wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
