################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-1, 2560x1440@164.84Hz, 0x0, 1
monitor = DP-2, 2560x1440@164.84Hz, 2560x0, 1
monitor = DP-3, 2560x1440@164.84Hz, 5120x0, 1

# fallback for new Monitors
monitor = ,preferred,auto,auto

# Workspace-Monitor Binding
# DP-1 (links): 1, 4, 7, 10
workspace = 1, monitor:DP-1, default:true
workspace = 4, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 10, monitor:DP-1

# DP-2 (mitte): 2, 5, 8
workspace = 2, monitor:DP-2, default:true
workspace = 5, monitor:DP-2
workspace = 8, monitor:DP-2

# DP-3 (rechts): 3, 6, 9
workspace = 3, monitor:DP-3, default:true
workspace = 6, monitor:DP-3
workspace = 9, monitor:DP-3

cursor {
    default_monitor = DP-2
}
