###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty -o hide_window_decorations=yes
$fileManager = dolphin
$menu = walker
